select * from [dbo].[salesData]

--Analysis

-- this is to analyse best month for sales in each year
select MONTH_ID month_of_2003  , COUNT(ORDERNUMBER) TOTAL_ORDER ,SUM(SALES) TOTAL_SALES FROM [dbo].[salesData]
WHERE YEAR_ID = 2005
GROUP BY MONTH_ID
ORDER BY 2 DESC


-- conclusion Nov. is best month for sales.
-- Ques-- best product for Nov. month.
select  COUNT(ORDERNUMBER) TOTAL_ORDER ,PRODUCTLINE ,SUM(SALES) TOTAL_SALES FROM [dbo].[salesData]
WHERE MONTH_ID = 11
GROUP BY PRODUCTLINE
ORDER BY TOTAL_SALES DESC

--Ques -- best customer

WITH CUSTOMER_DETAILS AS
(select CUSTOMERNAME , sum(SALES) TOTALPURCHASE , COUNT(ORDERNUMBER) FREQUENCY , MAX(ORDERDATE) LASTORDERDATE,AVG(SALES) AVERAGEDSALE,
(SELECT MAX(ORDERDATE) FROM [dbo].[salesData])  RECENTORDERDATE,
DATEDIFF(DD, MAX(ORDERDATE) ,(SELECT MAX(ORDERDATE) FROM [dbo].[salesData])) RECENCY
FROM [dbo].[salesData]
GROUP BY CUSTOMERNAME
)

SELECT * ,
NTILE(3) OVER (ORDER BY RECENCY ASC) RECENT,
NTILE(3) OVER (ORDER BY TOTALPURCHASE) MANETARYVALUE,
NTILE(3) OVER (ORDER BY FREQUENCY) FREQUENT
FROM CUSTOMER_DETAILS
ORDER BY RECENT 

select COUNT (distinct CUSTOMERNAME) FROM [dbo].[salesData]



